[tox]
envlist = py310-django42, py312-django52, py313-django6
isolated_build = true

[testenv]
deps =
    pytest
    django42: Django>=4.2,<5.0
    django52: Django>=5.2,<5.3
    django6: Django>=6.0,<7.0
commands = pytest -q {posargs}
